// <auto-generated />
using DAL.EFcore.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DAL.EFcore.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.EFcore.Entyties.EfRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("EfRoutes");
                });

            modelBuilder.Entity("DAL.EFcore.Entyties.EfStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EfRouteId");

                    b.Property<string>("NameCh");

                    b.Property<string>("NameEng");

                    b.Property<string>("NameRu");

                    b.HasKey("Id");

                    b.HasIndex("EfRouteId");

                    b.ToTable("EfStations");
                });

            modelBuilder.Entity("DAL.EFcore.Entyties.EfStation", b =>
                {
                    b.HasOne("DAL.EFcore.Entyties.EfRoute", "EfRoute")
                        .WithMany("Stations")
                        .HasForeignKey("EfRouteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
